// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjOQIAeP1KvR7U9BzBLfndN42_ogzOY_M',
    appId: '1:77667461062:web:91b871e7eb6bcdc4b574c7',
    messagingSenderId: '77667461062',
    projectId: 'smart-note-p05032026',
    authDomain: 'smart-note-p05032026.firebaseapp.com',
    storageBucket: 'smart-note-p05032026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqAJzW1J7EgpDKcP1x_9E_i9xxMesdhVM',
    appId: '1:77667461062:android:1569cc435cf8341eb574c7',
    messagingSenderId: '77667461062',
    projectId: 'smart-note-p05032026',
    storageBucket: 'smart-note-p05032026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkCx64KsMI_fKDVkfefBWsgYV_hQKNVog',
    appId: '1:77667461062:ios:361200af98d0ecbbb574c7',
    messagingSenderId: '77667461062',
    projectId: 'smart-note-p05032026',
    storageBucket: 'smart-note-p05032026.firebasestorage.app',
    iosBundleId: 'com.example.noteFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjOQIAeP1KvR7U9BzBLfndN42_ogzOY_M',
    appId: '1:77667461062:web:a586b5f5f08ba3afb574c7',
    messagingSenderId: '77667461062',
    projectId: 'smart-note-p05032026',
    authDomain: 'smart-note-p05032026.firebaseapp.com',
    storageBucket: 'smart-note-p05032026.firebasestorage.app',
  );

}